name: Build and Release LaTeX document

on:
  push:
    branches: [ main ]
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          
      - name: stash pdf
        run: |
          mv main.pdf $HOME # cache the file
          
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        with:
          # The branch to create
          branch: gh_actions_builds
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: checkout gh_actions_builds branch
        uses: actions/checkout@v1
        with:
          ref: gh_actions_builds 
          
      - name: commit pdf
        run: |
          git config --local user.email "raven.xu98@gmail.com"
          git config --local user.name "Raven Xu"
          mv $HOME/main.pdf $(pwd) # bring it back 
          git add main.pdf
          git commit -m "Updated by GitHub Action Automatically"
          
      - name: push pdf
        uses: ad-m/github-push-action@v0.5.0
        with: 
          branch: gh_actions_builds 
          force: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
